name: Issue Report
description: File an issue
title: "issue name"
labels: ["new issue", "triage"]
projects: ["connectRTC"]
assignees:
  -
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-issue
    attributes:
      label: What is a issue about?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "An issue happened!"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Brave
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: "Thanks for reporting an issue!"
